version: "2"
services:
  go-server:
    image: gocd/gocd-server:v17.12.0
    ports:
      - '8153:8153'
      - '8154:8154'
    volumes:
      - ./test/godata/config:/godata/config
      - ./test/godata/artifacts:/godata/artifacts

  go-agent:
    image: gocd/gocd-agent-ubuntu-16.04:v17.12.0
    links:
      - go-server
    environment:
      AGENT_AUTO_REGISTER_KEY: '123456789abcdef'
      GO_SERVER_URL: https://go-server:8154/go

  gorebuild:
    build:
      context: .
      dockerfile: Dockerfile.gorebuild
    links:
      - go-server
    environment:
      GO_SERVER_URL: https://go-server:8154/go
